apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ 'sh', '-c', 'mkdir -p /var/lib/grafana && chmod -R 777 /var/lib/grafana' ]
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana:10.2.3
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SERVER_ROOT_URL
              value: "https://monitoring.startsmallstarttoday.com/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_PROXY_ENABLED
              value: "true"
            - name: GF_AUTH_PROXY_HEADER_NAME
              value: "Remote-User"
            - name: GF_AUTH_PROXY_HEADER_PROPERTY
              value: "username"
            - name: GF_AUTH_PROXY_AUTO_SIGN_UP
              value: "true"
            - name: GF_USERS_AUTO_ASSIGN_ORG
              value: "true"
            - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
              value: "Admin"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: grafana-datasources
          configMap:
            name: grafana-datasources