apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ 'sh', '-c', 'mkdir -p /var/lib/grafana && chmod -R 777 /var/lib/grafana' ]
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana:10.2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          ports:
            - containerPort: 3000
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
