server.port=8080
spring.application.name=philosophizer
mail.smtp.host=${SMTP_HOST}
mail.smtp.port=${SMTP_PORT}
mail.smtp.username=${SMTP_USERNAME}
mail.smtp.password=${SMTP_PASSWORD}

mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.debug=false
