spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#batch job config
jobs.daily-email.enabled=${MAIL_JOB_ENABLED}
#jobs.daily-email.cron= "0 0 7 * * *"
#spring.jackson.time-zone = "America/New York"
