# DB comes from env (RDS later)
spring.jpa.hibernate.ddl-auto=validate

# Mail comes from env
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#batch job config
jobs.daily-email.enabled=${MAIL_JOB_ENABLED}
