server.port=8080
spring.application.name=philosophizer

#smtp config
#mail.smtp.host=${SMTP_HOST:localhost}
#mail.smtp.port=${SMTP_PORT:1025}
#mail.smtp.username=${SMTP_USERNAME}
#mail.smtp.password=${SMTP_PASSWORD}
#mail.smtp.auth=${SMTP_AUTH_BOOL:false}
#mail.smtp.starttls.enable=${SMTP_START_TLS_BOOL:false}
#mail.smtp.debug=false
#mail.from=${MAIL_FROM_ADDRESS:noreply@local.dev}

#logging config
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n

#health probes
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
management.health.readinessstate.enabled=true
management.metrics.tags.application=philosophizer











