server.port=8080
spring.application.name=philosophizer
mail.smtp.host=${SMTP_HOST:localhost}
mail.smtp.port=${SMTP_PORT:1025}
mail.smtp.username=${SMTP_USERNAME}
mail.smtp.password=${SMTP_PASSWORD}

mail.smtp.auth=${SMTP_AUTH_BOOL:false}
mail.smtp.starttls.enable=${SMTP_START_TLS_BOOL:false}
mail.smtp.debug=false
mail.from=${MAIL_FROM_ADDRESS:noreply@local.dev}


logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n

