# environment
app.env=uat

# DB
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://${RDS_HOST}:5432/philosophizerdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

# H2 console - disabled
spring.h2.console.enabled=false

# Mail comes from env
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# batch job config
jobs.daily-email.enabled=${MAIL_JOB_ENABLED}

# prometheus env labeling
management.metrics.tags.env=uat

