spring.jpa.hibernate.ddl-auto=none

mail.smtp.host=${SMTP_HOST}
mail.smtp.port=${SMTP_PORT}
mail.smtp.username=${SMTP_USERNAME}
mail.smtp.password=${SMTP_PASSWORD}
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.from=${MAIL_FROM_ADDRESS}
mail.send.enabled=true

#batch job config
jobs.daily-email.enabled=${MAIL_JOB_ENABLED}
#jobs.daily-email.cron= "0 0 7 * * *"
#spring.jackson.time-zone = "America/New York"
