# DB comes from env (RDS later)
spring.jpa.hibernate.ddl-auto=validate

# Mail comes from env
mail.smtp.host=${SMTP_HOST}
mail.smtp.port=${SMTP_PORT}
mail.smtp.username=${SMTP_USERNAME}
mail.smtp.password=${SMTP_PASSWORD}
mail.smtp.auth=${SMTP_AUTH_BOOL:true}
mail.smtp.starttls.enable=${SMTP_START_TLS_BOOL:true}
mail.from=${MAIL_FROM_ADDRESS}

#batch job config
jobs.daily-email.enabled=${MAIL_JOB_ENABLED}
