mail.smtp.host=localhost
mail.smtp.port=1025
mail.smtp.username=
mail.smtp.password=
mail.smtp.auth=false
mail.smtp.starttls-enable=false
mail.smtp.from=test@local.dev
mailhog.api.url=http://localhost:8025


# Local DB
spring.datasource.url=jdbc:h2:mem:philosophizerdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# H2 console (local only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console