# disable web server
spring.main.web-application-type=none

# environment
app.env=uat  # or prod, depending on cluster

# DB
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://${RDS_HOST}:5432/philosophizerdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.flyway.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
# explicit guard
app.mode=job

# Jobs
jobs.daily-email.enabled=true

# Mail comes from env (SES)
spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from=jk0827@gmail.com