apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: auth
data:
  users_database.yml: |
    users:
      jack:
        password: "$argon2id$v=19$m=65536,t=3,p=4$8NJ7nH+kZ5UAgir0vm9Pvw$jw/AwBZiqktiFVOAo7KTxdV9OaPaTI7BEgCo++1+RSM"
        displayname: "Jack"
        email: "jk0827@gmail.com"
        groups:
          - admins
        disabled: false