apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: auth
type: Opaque
stringData:
  JWT_SECRET: "vRYNEaJw20depHF9lgKxobcd53Duo7FluDIoP7xqoJJaH6DO3RaWqjbvuMuEGeG0"
  SESSION_SECRET: "bSyV1UCVOStoLqKFLbamwq131zhoKqG1kAkzEu1WaaSXa8fmxhLXDtMW40gZXNSI"
  STORAGE_ENCRYPTION_KEY: "kaKDLIkkwQTdOeoMlKkiV6lDGY2UiSpzjiQmggiwgNkyJjuXm7qNHTWTIlHxomI6"