apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: auth
data:
  configuration.yml: |
    server:
      address: tcp://0.0.0.0:9091/

    log:
      level: debug

    session:
      name: authelia_session
      secret: "{{ env \"AUTHELIA_SESSION_SECRET\" }}"
      expiration: 1h
      inactivity: 5m
      cookies:
        - domain: startsmallstarttoday.com

    authentication_backend:
      file:
        path: /config/users_database.yml

    access_control:
      default_policy: deny
      rules:
        - domain: "app.startsmallstarttoday.com"
          policy: one_factor

    storage:
      encryption_key: '{{ env "AUTHELIA_STORAGE_ENCRYPTION_KEY" }}'
      local:
        path: /data/db.sqlite3

    notifier:
      filesystem:
        filename: /data/notification.txt