apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: auth
data:
  users_database.yml: |
    users:
      jack:
        password: "$argon2id$v=19$m=65536,t=3,p=4$tV5Z0i8BW/1I8yDJM8dDCg$dvWCpi4Gua1D70IlQJ/FotD36f/jui99uh+n8P2KJEU"
        displayname: "Jack"
        email: "jk0827@gmail.com"
        groups:
          - admins
        disabled: false