apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
  labels:
    app: promtail
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: philosophizer-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: philosophizer
              namespace: default
              env: uat
              __path__: /var/log/pods/default_philosophizer*/**/*.log

        pipeline_stages:
          - cri: {}
          - json:
              expressions:
                log: log
          - json:
              source: log
              expressions:
                level: level
                message: message
                service: service
          - labels:
              level:
              service:
          - output:
              source: message