apiVersion: apps/v1
kind: Deployment
metadata:
  name: philosophizer
  namespace: philosophizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: philosophizer
  template:
    metadata:
      labels:
        app: philosophizer
    spec:
      containers:
        - name: philosophizer
          image: 733232591650.dkr.ecr.us-east-1.amazonaws.com/philosophizer/uat:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: RDS_HOST
              valueFrom:
                secretKeyRef:
                  name: philosophizer-db-secret
                  key: RDS_HOST
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: philosophizer-db-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: philosophizer-db-secret
                  key: RDS_PASSWORD
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: philosophizer-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: philosophizer-secrets
                  key: SMTP_PASSWORD
            - name: MAIL_JOB_ENABLED
              valueFrom:
                secretKeyRef:
                  name: philosophizer-secrets
                  key: MAIL_JOB_ENABLED