apiVersion: apps/v1
kind: Deployment
metadata:
  name: philosophizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: philosophizer
  template:
    metadata:
      labels:
        app: philosophizer
    spec:
      containers:
        - name: philosophizer
          image: philosophizer:latest   # placeholder
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: philosophizer-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: philosophizer-secrets
                  key: SMTP_PASSWORD
            - name: MAIL_JOB_ENABLED
              valueFrom:
                secretKeyRef:
                  name: philosophizer-secrets
                  key: MAIL_JOB_ENABLED