apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: philosophizer-db-secret
  namespace: philosophizer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: philosophizer-db-secret
    creationPolicy: Owner
  data:
    - secretKey: RDS_HOST
      remoteRef:
        key: philosophizer-uat/db
        property: host
    - secretKey: RDS_USERNAME
      remoteRef:
        key: philosophizer-uat/db
        property: username
    - secretKey: RDS_PASSWORD
      remoteRef:
        key: philosophizer-uat/db
        property: password