apiVersion: apps/v1
kind: Deployment
metadata:
  name: philosophizer
spec:
  template:
    metadata:
      labels:
        app: philosophizer
        env: uat
    spec:
      containers:
        - name: philosophizer
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: uat