resources:
  - ../../base
  - philosophizer-external-secret.yaml
  - philosophizer-ingress.yaml

patches:
  - path: deployment-env.yaml
    target:
      kind: Deployment
      name: philosophizer
  - path: cronjob-env.yaml
    target:
      kind: CronJob
      name: philosophizer-daily-email

images:
  - name: philosophizer
    newName: 733232591650.dkr.ecr.us-east-1.amazonaws.com/philosophizer/uat
    newTag: latest

namespace: philosophizer